//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class allunitstatistic
    {
        public string UnitId { get; set; }
        public System.DateTime DateTime_Statics { get; set; }
        public float System_heat { get; set; }
        public Nullable<float> Conventional_energy { get; set; }
        public Nullable<float> Storage_tank { get; set; }
        public Nullable<float> System_efficiency { get; set; }
        public Nullable<float> Solar_assurance_day { get; set; }
        public Nullable<float> Solar_assurance_year { get; set; }
        public Nullable<float> Energy_alternative { get; set; }
        public Nullable<float> Carbon_emission { get; set; }
        public Nullable<float> Sulfur_emission { get; set; }
        public Nullable<float> Dust_emission { get; set; }
        public Nullable<float> Fee_effect { get; set; }
    }
}
