//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class union
    {
        public string UnitId { get; set; }
        public string alias { get; set; }
        public float Aera_IrradiatedSum { get; set; }
        public float Volumn_HeatingBox { get; set; }
        public float Flow_CollectorSys { get; set; }
        public float Flow_HeatUsing { get; set; }
        public float Auxiliary_power { get; set; }
        public float System_heat { get; set; }
        public Nullable<short> gprsstate { get; set; }
        public Nullable<System.DateTime> Star_time { get; set; }
        public Nullable<int> time_online { get; set; }
    }
}
