//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitstate
    {
        public string UnitId { get; set; }
        public System.DateTime DateTime_RecvDate { get; set; }
        public Nullable<float> Temp_HeatingBox { get; set; }
        public Nullable<float> Temp_CollectorBox { get; set; }
        public Nullable<float> Temp_CollectorIn { get; set; }
        public Nullable<float> Temp_CollectorOut { get; set; }
        public Nullable<float> Temp_Ambient { get; set; }
        public Nullable<float> Humidity_Ambient { get; set; }
        public Nullable<float> Speed_Wind { get; set; }
        public Nullable<int> SystemState { get; set; }
        public Nullable<int> ErrorState { get; set; }
        public Nullable<float> Amount_Irradiated { get; set; }
        public Nullable<float> Amount_IrradiatedSum { get; set; }
        public int Delta_Time { get; set; }
    }
}
