//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitstatistic
    {
        public int UnitId { get; set; }
        public string System_heat { get; set; }
        public string Conventional_energy { get; set; }
        public string Storage_tank { get; set; }
        public string System_efficiency { get; set; }
        public string Solar_assurance_day { get; set; }
        public string Solar_assurance_year { get; set; }
        public string Energy_alternative { get; set; }
        public string Carbon_emission { get; set; }
        public string Sulfur_emission { get; set; }
        public string Dust_emission { get; set; }
        public string Fee_effect { get; set; }
        public System.DateTime DateTime_Statics { get; set; }
    }
}
