//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18010
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _1144584xfmz4mj86x48wge {
            get {
                object obj = ResourceManager.GetObject("1144584xfmz4mj86x48wge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 确定退出吗？ 的本地化字符串。
        /// </summary>
        internal static string FMain_FMainClosing_ {
            get {
                return ResourceManager.GetString("FMain_FMainClosing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string FMain_Timer3Tick_信息 {
            get {
                return ResourceManager.GetString("FMain_Timer3Tick_信息", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数查询成功 的本地化字符串。
        /// </summary>
        internal static string FMain_Timer3Tick_参数查询成功 {
            get {
                return ResourceManager.GetString("FMain_Timer3Tick_参数查询成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数设置成功 的本地化字符串。
        /// </summary>
        internal static string FMain_Timer3Tick_参数设置成功 {
            get {
                return ResourceManager.GetString("FMain_Timer3Tick_参数设置成功", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string FMain_中心参数设置ToolStripMenuItemClick_提示 {
            get {
                return ResourceManager.GetString("FMain_中心参数设置ToolStripMenuItemClick_提示", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先关闭服务! 的本地化字符串。
        /// </summary>
        internal static string FMain_中心参数设置ToolStripMenuItemClick_请先关闭服务_ {
            get {
                return ResourceManager.GetString("FMain_中心参数设置ToolStripMenuItemClick_请先关闭服务_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务停止 的本地化字符串。
        /// </summary>
        internal static string FMain_停止服务ToolStripMenuItemClick_服务停止 {
            get {
                return ResourceManager.GetString("FMain_停止服务ToolStripMenuItemClick_服务停止", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务启动 的本地化字符串。
        /// </summary>
        internal static string FMain_启动数据中心ToolStripMenuItemClick_服务启动 {
            get {
                return ResourceManager.GetString("FMain_启动数据中心ToolStripMenuItemClick_服务启动", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要清除数据库记录么？ 的本地化字符串。
        /// </summary>
        internal static string FMain_数据清除ToolStripMenuItemClick_ {
            get {
                return ResourceManager.GetString("FMain_数据清除ToolStripMenuItemClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除确认 的本地化字符串。
        /// </summary>
        internal static string FMain_数据清除ToolStripMenuItemClick_清除确认 {
            get {
                return ResourceManager.GetString("FMain_数据清除ToolStripMenuItemClick_清除确认", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该采集点添加成功！ 的本地化字符串。
        /// </summary>
        internal static string FNodeManager_button_ADD_Click_ {
            get {
                return ResourceManager.GetString("FNodeManager_button_ADD_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该用户删除成功！ 的本地化字符串。
        /// </summary>
        internal static string FNodeManager_button_Del_Click_ {
            get {
                return ResourceManager.GetString("FNodeManager_button_Del_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该采集点名称修改成功！ 的本地化字符串。
        /// </summary>
        internal static string FNodeManager_button_Modify_Click_ {
            get {
                return ResourceManager.GetString("FNodeManager_button_Modify_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_open_sharp_thick {
            get {
                object obj = ResourceManager.GetObject("folder open sharp thick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 时间小时值需在范围（0-23）！ 的本地化字符串。
        /// </summary>
        internal static string Global_checkHour_ {
            get {
                return ResourceManager.GetString("Global_checkHour_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间分钟值需在范围（0-59）！ 的本地化字符串。
        /// </summary>
        internal static string Global_CheckMinute_ {
            get {
                return ResourceManager.GetString("Global_CheckMinute_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度值需在范围（0-100）！ 的本地化字符串。
        /// </summary>
        internal static string Global_CheckTemp_ {
            get {
                return ResourceManager.GetString("Global_CheckTemp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress... 的本地化字符串。
        /// </summary>
        internal static string MySqlBackupRestore_NewProgressForm_Progress___ {
            get {
                return ResourceManager.GetString("MySqlBackupRestore_NewProgressForm_Progress___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap quxian1 {
            get {
                object obj = ResourceManager.GetObject("quxian1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap quxian2 {
            get {
                object obj = ResourceManager.GetObject("quxian2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap quxian3 {
            get {
                object obj = ResourceManager.GetObject("quxian3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap quxian4 {
            get {
                object obj = ResourceManager.GetObject("quxian4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap system {
            get {
                object obj = ResourceManager.GetObject("system", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
