create database if not exists `db_tiger` /*!40100 DEFAULT CHARACTER SET utf8 */;
use `db_tiger`;
create table if not exists `tb_union_list` (  `UnitId` varchar(20) NOT NULL,  `gprs_state` int(11) DEFAULT NULL,  `alias` varchar(45) NOT NULL,  `Aera_IrradiatedSum` int(11) NOT NULL COMMENT '集热器面积',  `Volumn_HeatingBox` int(11) NOT NULL COMMENT '贮热水箱容量',  `Start_time` datetime DEFAULT NULL,  `Stop_time` datetime DEFAULT NULL,  `time_online` int(11) DEFAULT NULL,  PRIMARY KEY (`UnitId`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
delete from `tb_union_list`;
insert into `tb_union_list` value ('130','50','HENAN','801','8000',null,null,'500'),('132','4','JIANGSU','201','3000',null,null,'80'),('135','3','ANHUI','501','5000',null,null,'59'),('136','4','ZHEJIANG','850','8333',null,null,'80'),('13695655652','5','HFUU','101','2000',null,null,'20');
create table if not exists `tb_unit_state` (  `Temp_HeatingBox` varchar(20) DEFAULT NULL COMMENT '供热水箱温度',  `Temp_CollectorBox` varchar(20) DEFAULT NULL COMMENT '集热水箱温度',  `Temp_CollectorIn` varchar(20) DEFAULT NULL COMMENT '集热系统进口温度',  `Temp_CollectorOut` varchar(20) DEFAULT NULL COMMENT '集热系统出口温度',  `Temp_Ambient` varchar(20) DEFAULT NULL COMMENT '环境温度',  `Humidity_Ambient` varchar(20) DEFAULT NULL COMMENT '环境湿度',  `Speed_Wind` varchar(20) DEFAULT NULL COMMENT '风速',  `SystemState` varchar(20) DEFAULT NULL COMMENT '系统状态',  `ErrorState` varchar(20) DEFAULT NULL COMMENT '系统故障状态',  `UnitId` int(11) NOT NULL COMMENT '用户单元ID',  `DateTime_RecvDate` datetime NOT NULL COMMENT '数据采集时间',  `Amount_Irradiated` varchar(45) DEFAULT NULL COMMENT '太阳能辐照量',  `Amount_IrradiatedSum` varchar(45) DEFAULT NULL COMMENT '总辐照量',  PRIMARY KEY (`UnitId`,`DateTime_RecvDate`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
delete from `tb_unit_state`;
create table if not exists `tb_unit_statistics` (  `UnitId` int(11) NOT NULL,  `System_heat` varchar(20) DEFAULT NULL COMMENT '集热系统得热量',  `Conventional_energy` varchar(20) DEFAULT NULL COMMENT '系统常规热源耗能量',  `Storage_tank` varchar(20) DEFAULT NULL COMMENT '贮热水箱热损系数',  `System_efficiency` varchar(20) DEFAULT NULL COMMENT '集热系统效率',  `Solar_assurance_day` varchar(20) DEFAULT NULL COMMENT '日太阳能保证率',  `Solar_assurance_year` varchar(20) DEFAULT NULL COMMENT '全年太阳能保证率',  `Energy_alternative` varchar(20) DEFAULT NULL COMMENT '常规能源替代量',  `Carbon_emission` varchar(20) DEFAULT NULL COMMENT '二氧化碳减排量',  `Sulfur_emission` varchar(20) DEFAULT NULL COMMENT '二氧化硫减排量',  `Dust_emission` varchar(20) DEFAULT NULL COMMENT '粉尘减排量',  `Fee_effect` varchar(20) DEFAULT NULL COMMENT '项目费效比',  `DateTime_Statics` datetime NOT NULL,  PRIMARY KEY (`UnitId`,`DateTime_Statics`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
delete from `tb_unit_statistics`;
